name: TFLint and Terraform Plan

on:
  pull_request:
    branches:
      - main

jobs:
  tflint-and-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.7.5

      - name: Install TFLint
        run: curl -L "$(curl -s https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E "https://.+?_linux_amd64.zip")" -o tflint.zip && unzip tflint.zip && chmod +x tflint && sudo mv tflint /usr/local/bin/

      - name: Run TFLint
        run: tflint

      - name: Terraform Plan
        run: terraform plan
